# Generated by Django 4.2.4 on 2023-09-21 07:54

from django.db import migrations
from django.contrib.auth import get_user_model


def generate_superuser(apps, schema_editor):
    User = get_user_model()
    u = User()
    u.cellphone = "+989120787285"
    u.username = u.cellphone
    u.first_name = "saeed"
    u.last_name = "rahimi"
    u.set_password("152490")
    u.is_superuser = True
    u.is_staff = True
    u.save()


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
