# Generated by Django 4.2.4 on 2023-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_category_deleted_phrase_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='link',
            field=models.JSONField(default=dict),
        ),
    ]
