# Generated by Django 4.2.6 on 2023-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.TextField(blank=True, null=True)),
                ('title_1', models.TextField(blank=True, db_column='title 1', null=True)),
                ('title_2', models.TextField(blank=True, db_column='title 2', null=True)),
                ('title_3', models.TextField(blank=True, db_column='title 3', null=True)),
                ('type', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
