apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride}}
data:
  REMOTEDB: "True"
  DATABASE_HOST: {{ .Values.configmap.DATABASE_HOST }}
  DATABASE_NAME: {{ .Values.configmap.DATABASE_NAME }}
  DATABASE_USER: {{ .Values.configmap.DATABASE_USER }}
  DATABASE_PASSWORD: {{ .Values.configmap.DATABASE_PASSWORD }}
  DATABASE_PORT: "{{ .Values.configmap.DATABASE_PORT }}"
  VERSION: "{{ .Values.image.tag }}"
